"""
Per-mapping log rotation + time-range log search.

Rotation: every mapping's access/error logs get a logrotate stanza — daily,
dateext, keep N days, optional gzip — from the mapping's "logrotate" snippet
(Snippets page) or the global default (Settings). The app writes the config
to DATA_DIR and runs the real `logrotate` binary from a daemon thread once an
hour (logrotate's own state file decides whether a daily rotation is due), and
`nginx -s reopen` makes nginx switch to the fresh files. Rotated files look
like `<domain>.<port>-access.log-20260909[.gz]`, next to the live log.

Search: `search()` walks the live file plus every rotated archive (plain or
gzip), oldest first, and yields lines whose timestamp falls inside a window —
so "what happened two days ago at 15:40" works after rotation too.
"""
import datetime
import glob
import gzip
import os
import re
import shlex
import subprocess
import threading
import time

import config
import storage

INTERVAL = 3600           # seconds between logrotate runs (it self-limits to daily)
CONF_PATH = os.path.join(config.DATA_DIR, "logrotate.conf")
STATE_PATH = os.path.join(config.DATA_DIR, "logrotate.state")
DEFAULTS = {"keep_days": 7, "compress": True, "max_size": None}
_last = {"ran": None, "ok": None, "output": "", "rotated": 0}
_scheduler_started = False


# --------------------------------------------------------------------------
# Policy resolution
# --------------------------------------------------------------------------
def default_policy():
    s = storage.settings_all()
    return {"keep_days": int(s.get("log_keep_days", DEFAULTS["keep_days"])),
            "compress": bool(s.get("log_compress", DEFAULTS["compress"])),
            "max_size": s.get("log_max_size") or None, "source": "default"}


def policy_for(mapping):
    """The rotation policy in force for a mapping: its logrotate snippet, else
    the global default."""
    for ref in mapping.get("snippets") or []:
        if ref.startswith("logrotate:"):
            rec = storage.snip_get("logrotate", ref.split(":", 1)[1])
            if rec:
                return {"keep_days": int(rec.get("keep_days") or DEFAULTS["keep_days"]),
                        "compress": bool(rec.get("compress")),
                        "max_size": rec.get("max_size") or None,
                        "source": "snippet:" + rec["name"]}
    return default_policy()


def describe(pol):
    bits = [f"keep {pol['keep_days']} days", "gzip" if pol.get("compress") else "no compression"]
    if pol.get("max_size"):
        bits.append(f"or when over {pol['max_size']}")
    return ", ".join(bits)


# --------------------------------------------------------------------------
# logrotate config
# --------------------------------------------------------------------------
def _nginx_reopen_cmd():
    argv = (shlex.split(config.SUDO) if config.SUDO else []) + [config.NGINX_BIN, "-s", "reopen"]
    return " ".join(shlex.quote(a) for a in argv)


def render_conf(mappings=None):
    """One stanza per mapping log directory. `dateext` gives the
    -YYYYMMDD suffix the search() reader understands; `missingok`/`notifempty`
    keep logrotate quiet for mappings that never got traffic."""
    import nginx_manager as nm
    mappings = storage.list_mappings() if mappings is None else mappings
    out = ["# Generated by Splitter — per-mapping nginx log rotation. Do not edit.",
           f"# Regenerated before every run; runs hourly, rotates daily (state: {STATE_PATH}).", ""]
    for m in sorted(mappings, key=lambda x: (x["domain"], x.get("listen_port") or 0)):
        port = m.get("listen_port") or config.LISTEN_PORT
        pol = policy_for(m)
        paths = nm.log_paths_for(m["domain"], port)
        out.append(f"# {m['domain']}:{port} — {describe(pol)} ({pol['source']})")
        out.append(" ".join(shlex.quote(p) for p in paths.values()) + " {")
        out += ["    daily", "    dateext", "    dateformat -%Y%m%d",
                f"    rotate {pol['keep_days']}", f"    maxage {pol['keep_days']}",
                "    missingok", "    notifempty", "    nocreate"]
        if pol.get("max_size"):
            out.append(f"    maxsize {pol['max_size']}")
        out += ["    compress", "    delaycompress"] if pol.get("compress") else ["    nocompress"]
        out += ["    sharedscripts", "    postrotate",
                f"        {_nginx_reopen_cmd()} >/dev/null 2>&1 || true",
                "    endscript", "}", ""]
    return "\n".join(out)


def run_once(force=False):
    """Regenerate the config and run logrotate. Returns a result dict."""
    global _last
    conf = render_conf()
    if config.SIMULATE:
        _last = {"ran": _now_iso(), "ok": True, "output": "[simulated] would run logrotate", "rotated": 0}
        return {**_last, "conf": conf}
    os.makedirs(config.DATA_DIR, exist_ok=True)
    with open(CONF_PATH, "w", encoding="utf-8") as fh:
        fh.write(conf)
    os.chmod(CONF_PATH, 0o644)
    argv = ["logrotate", "-s", STATE_PATH] + (["-f"] if force else []) + [CONF_PATH]
    try:
        proc = subprocess.run(argv, capture_output=True, text=True, timeout=300)
        output = (proc.stdout + proc.stderr).strip()
        ok = proc.returncode == 0
    except FileNotFoundError:
        output, ok = "logrotate is not installed (apt install logrotate)", False
    except subprocess.TimeoutExpired:
        output, ok = "logrotate timed out", False
    _last = {"ran": _now_iso(), "ok": ok, "output": output[-4000:], "forced": force}
    return {**_last, "conf": conf}


def status():
    return {**_last, "conf_path": CONF_PATH, "installed": _installed(), "default": default_policy()}


def _installed():
    if config.SIMULATE:
        return True
    from shutil import which
    return which("logrotate") is not None


def _now_iso():
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def start_scheduler():
    global _scheduler_started
    if _scheduler_started or config.SIMULATE:
        return
    _scheduler_started = True

    def _loop():
        time.sleep(120)   # let nginx / the app settle after boot
        while True:
            try:
                run_once()
            except Exception:
                pass
            time.sleep(INTERVAL)

    threading.Thread(target=_loop, name="logrotate-scheduler", daemon=True).start()


# --------------------------------------------------------------------------
# Time-range search across live + rotated files
# --------------------------------------------------------------------------
_MONTHS = {m: i for i, m in enumerate(
    ("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"), 1)}
_RE_CLF = re.compile(r"\[(\d{2})/([A-Za-z]{3})/(\d{4}):(\d{2}):(\d{2}):(\d{2}) ([+-]\d{4})\]")
_RE_ISO = re.compile(r"(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.\d+)?(Z|[+-]\d{2}:?\d{2})")
_RE_ERR = re.compile(r"^(\d{4})/(\d{2})/(\d{2}) (\d{2}):(\d{2}):(\d{2}) ")
_RE_SUFFIX = re.compile(r"-(\d{8})(?:\.gz)?$")


def _tz(off):
    if off in ("Z", "+0000", "+00:00"):
        return datetime.timezone.utc
    sign = 1 if off[0] == "+" else -1
    digits = off[1:].replace(":", "")
    return datetime.timezone(sign * datetime.timedelta(hours=int(digits[:2]), minutes=int(digits[2:])))


def line_time(line):
    """UTC datetime of a log line, or None if no recognised timestamp."""
    m = _RE_CLF.search(line)
    if m:
        d, mon, y, H, M, S, off = m.groups()
        mo = _MONTHS.get(mon.title())
        if mo:
            return datetime.datetime(int(y), mo, int(d), int(H), int(M), int(S), tzinfo=_tz(off)).astimezone(datetime.timezone.utc)
    m = _RE_ISO.search(line)
    if m:
        y, mo, d, H, M, S, off = m.groups()
        return datetime.datetime(int(y), int(mo), int(d), int(H), int(M), int(S), tzinfo=_tz(off)).astimezone(datetime.timezone.utc)
    m = _RE_ERR.match(line)
    if m:   # nginx error log: local time, no offset
        y, mo, d, H, M, S = (int(x) for x in m.groups())
        local = datetime.datetime(y, mo, d, H, M, S).astimezone()   # system tz
        return local.astimezone(datetime.timezone.utc)
    return None


def log_files(path):
    """The live file plus its rotated siblings, oldest first:
    [{path, name, size, mtime, date (YYYYMMDD or None), compressed}]."""
    out = []
    cands = [p for p in glob.glob(path + "-*") if _RE_SUFFIX.search(p)]
    if os.path.exists(path):
        cands.append(path)
    for p in cands:
        try:
            st = os.stat(p)
        except OSError:
            continue
        m = _RE_SUFFIX.search(p)
        out.append({"path": p, "name": os.path.basename(p), "size": st.st_size,
                    "mtime": datetime.datetime.fromtimestamp(st.st_mtime, datetime.timezone.utc).isoformat(timespec="seconds"),
                    "date": m.group(1) if m and p != path else None, "compressed": p.endswith(".gz"),
                    "live": p == path})
    out.sort(key=lambda f: (f["date"] or "99999999", f["name"]))
    return out


def _open(path):
    return gzip.open(path, "rt", encoding="utf-8", errors="replace") if path.endswith(".gz") \
        else open(path, "r", encoding="utf-8", errors="replace")


def search(path, start, end, query=None, limit=5000):
    """Lines from every file of `path` (live + rotated) whose timestamp is in
    [start, end] (aware datetimes), optionally containing `query`. Returns
    {lines, files, truncated, scanned}. Files whose rotation date is clearly
    outside the window are skipped without reading."""
    start_day = (start - datetime.timedelta(days=1)).strftime("%Y%m%d")
    end_day = (end + datetime.timedelta(days=1)).strftime("%Y%m%d")
    lines, files, scanned, truncated = [], [], 0, False
    for f in log_files(path):
        # a rotated file dated D holds lines up to D (and, with delaycompress,
        # possibly a little after) — skip files that can't overlap the window.
        if f["date"] and (f["date"] < start_day or f["date"] > end_day):
            continue
        matched = 0
        try:
            with _open(f["path"]) as fh:
                for raw in fh:
                    scanned += 1
                    if query and query not in raw:
                        continue
                    t = line_time(raw)
                    if t is None or t < start or t > end:
                        continue
                    lines.append(f"{f['date'] or 'live'}  {raw.rstrip()}")
                    matched += 1
                    if len(lines) >= limit:
                        truncated = True
                        break
        except OSError:
            continue
        files.append({**f, "matched": matched})
        if truncated:
            break
    return {"lines": lines, "files": files, "truncated": truncated, "scanned": scanned}
